### PR TITLE
handling touch input

### PR DESCRIPTION
**Pull request by bradgearon**
handling mouse move/up on document to handle move out / mouse up scenario
added index.html for testing locally (uses web video for camera stream)

resolves ChurchCRM/CRM/#2016

### CODE REVIEW

**Review by crossan007 — CHANGES_REQUESTED** [review]
There is already an index.html for testing this plugin locally.

There's also a vagrant environment with HTTPS....

**Comment by bradgearon** [comment]
oh no. I'm such a doofus! sorry, I'll fix that.

**Comment by crossan007** [comment]
you also need to SSH into the box right now to /var/www/public, and run npm install.

I have to do some changes to the vagrant file so that it automatically runs the installer.

**Review by crossan007 — CHANGES_REQUESTED** [review]
Any chance you can get pinch to resize working?

**Review by crossan007 — APPROVED** [review]

**Comment by bradgearon** [comment]
I'd love to. Might make it easier and use hammer. But I'll start looking into it. Thanks!

**Comment by bradgearon** [comment]
I added pinch zoom, it works alright. Check it out yo!

**Comment by crossan007** [comment]
@bradgearon  thanks for this!  I'm hoping to have some time tomorrow morning to review all of my pending PRs :-)

**Comment by bradgearon** [comment]
No problem. Thank you!

**Review by crossan007 — APPROVED** [review]

**Pull request merged**
